---

- name: "Devspaces operator - Create operator subscription"
  kubernetes.core.k8s:
    state: present
    namespace: "{{ ocp4_workload_app_connectivity_workshop_devspaces_operator_namespace }}"
    definition: "{{ lookup('template', 'devspaces_operator/subscription.yaml.j2') | from_yaml }}"

- name: "Devspaces operator - Get Installed CSV"
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: devspaces
    namespace: "{{ ocp4_workload_app_connectivity_workshop_devspaces_operator_namespace }}"
  register: r_devspaces_subscription
  retries: 30
  delay: 10
  until:
    - r_devspaces_subscription.resources[0].status.currentCSV is defined
    - r_devspaces_subscription.resources[0].status.currentCSV | length > 0

- name: "Devspaces operator - Wait until CSV is installed"
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ r_devspaces_subscription.resources[0].status.currentCSV }}"
    namespace: "{{ ocp4_workload_app_connectivity_workshop_devspaces_operator_namespace }}"
  register: r_devspaces_csv
  retries: 40
  delay: 30
  until:
    - r_devspaces_csv.resources[0].status.phase is defined
    - r_devspaces_csv.resources[0].status.phase | length > 0
    - r_devspaces_csv.resources[0].status.phase == "Succeeded"

- name: Wait until the operator is up and running
  when: ocp4_workload_app_connectivity_workshop_devspaces_operator_wait_for_deploy | bool
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: deployment
    name: "{{ ocp4_workload_app_connectivity_workshop_devspaces_operator_deployment }}"
    namespace: "{{ ocp4_workload_app_connectivity_workshop_devspaces_operator_namespace }}"
  register: r_devspaces_deployment
  retries: 40
  delay: 15
  ignore_errors: true
  until:
    - r_devspaces_deployment.resources is defined
    - r_devspaces_deployment.resources | length | int > 0
    - r_devspaces_deployment.resources[0].status.availableReplicas is defined
    - r_devspaces_deployment.resources[0].status.availableReplicas | int == r_devspaces_deployment.resources[0].spec.replicas | int

- name: Create namespace for devspaces checluster - {{ ocp4_workload_app_connectivity_workshop_devspaces_namespace }}
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ ocp4_workload_app_connectivity_workshop_devspaces_namespace }}"
    state: present

- name: Deploy devspaces checluster
  kubernetes.core.k8s:
    state: present
    namespace: "{{ ocp4_workload_app_connectivity_workshop_devspaces_namespace }}"
    definition: "{{ lookup('template', 'devspaces-checluster.yaml.j2') }}"

- name: Wait until devspaces checluster is running
  ansible.builtin.uri:
    url: https://devspaces.{{ r_openshift_subdomain }}/dashboard/
    validate_certs: false
    status_code: 403
  register: result
  until: result.status == 403
  retries: 120
  delay: 15
  ignore_errors: true

- name: "Create namespaces for user devspaces"
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'devspaces-namespace.yaml.j2') }}"
  vars:
    r_app_connectivity_workshop_devspaces_namespaces:
      - name: "{{ ocp4_workload_app_connectivity_workshop_devspaces_user_namespace_prefix }}-user"
  retries: 10
  delay: 30
  ignore_errors: true

- name: "Create dev spaces template for users"
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'devspaces-devworkspace-template.yaml.j2') }}"
  vars:
    r_app_connectivity_workshop_devspaces_template_namespaces:
      - name: "{{ ocp4_workload_app_connectivity_workshop_devspaces_user_namespace_prefix }}-user"
  retries: 10
  delay: 30
  ignore_errors: true

- name: "Create dev spaces for users"
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'devspaces-devworkspace.yaml.j2') }}"
  vars:
    r_app_connectivity_workshop_devspaces_devworkspace_namespaces:
      - name: "{{ ocp4_workload_app_connectivity_workshop_devspaces_user_namespace_prefix }}-user"
  retries: 10
  delay: 30
  ignore_errors: true
