---

- name: Setup opentelemetry
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'opentelemetry.yaml.j2') | from_yaml }}"
  retries: 10
  delay: 30
  ignore_errors: true
  register: opentelemetry_result
  until: opentelemetry_result is not failed

- name: Print opentelemetry_result from the previous task
  ansible.builtin.debug:
    var: opentelemetry_result