---

# ---- Open Tempo Operator (tempo-product)

- name: install tempo-product operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_name: tempo-product
    install_operator_channel: "stable"
    install_operator_starting_csv: ""
    install_operator_catalogsource_setup: false
    install_operator_catalogsource_image: ""
    install_operator_catalogsource_image_tag: ""
    install_operator_csv_nameprefix: tempo-operator

- name: Wait until the operator is up and running
  when: ocp4_workload_app_connectivity_workshop_opentelemetry_product_wait_for_deploy | bool
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: deployment
    name: tempo-operator-controller
    namespace: openshift-operators
  register: r_tempo_deployment
  retries: 40
  delay: 15
  until:
    - r_tempo_deployment.resources is defined
    - r_tempo_deployment.resources | length | int > 0
    - r_tempo_deployment.resources[0].status.availableReplicas is defined
    - r_tempo_deployment.resources[0].status.availableReplicas | int == r_tempo_deployment.resources[0].spec.replicas | int
    - r_tempo_deployment is not failed
  ignore_errors: true

- name: Print travel_portal_result from the previous task
  ansible.builtin.debug:
    var: travel_portal_result

# ---- Setup tracing-system

- name: Setup tracing-system
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'tracing-system.yaml.j2') | from_yaml }}"
  retries: 10
  delay: 30
  ignore_errors: true
  register: tracing_system_result
  until: tracing_system_result is not failed

- name: Print tracing_system_result from the previous task
  ansible.builtin.debug:
    var: tracing_system_result
