---
# Setup travel_agency

- name: Setup travel_agency
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'travel_agency.yaml.j2') | from_yaml }}"
  retries: 10
  delay: 30
  ignore_errors: true
  register: travel_agency_result
  until: travel_agency_result is not failed

- name: Print travel_agency_result from the previous task
  ansible.builtin.debug:
    var: travel_agency_result

# Install travel_control

- name: Setup travel_control
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'travel_control.yaml.j2') | from_yaml }}"
  retries: 10
  delay: 30
  ignore_errors: true
  register: travel_control_result
  until: travel_control_result is not failed

- name: Print travel_control_result from the previous task
  ansible.builtin.debug:
    var: travel_control_result


# Install travel_portal

- name: Setup travel_portal
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'travel_portal.yaml.j2') | from_yaml }}"
  retries: 10
  delay: 30
  ignore_errors: true
  register: travel_portal_result
  until: travel_portal_result is not failed

- name: Print travel_portal_result from the previous task
  ansible.builtin.debug:
    var: travel_portal_result

# Install partner-blue-portal

- name: Setup partner-blue-portal
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'partner-blue-portal.yaml.j2') | from_yaml }}"
  retries: 10
  delay: 30
  ignore_errors: true
  register: partner_blue_portal_result
  until: partner_blue_portal_result is not failed

- name: Print partner_blue_portal_result from the previous task
  ansible.builtin.debug:
    var: partner_blue_portal_result
