---

- name: Setup travel-web
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'travel-web.yaml.j2') | from_yaml }}"
  retries: 10
  delay: 30
  ignore_errors: true
  register: travel_web_result
  until: travel_web_result is not failed

- name: Print travel_web_result from the previous task
  ansible.builtin.debug:
    var: travel_web_result
