---

- name: Setup webterminal
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'webterminal_application.yaml.j2') | from_yaml }}"
  retries: 10
  delay: 30
  ignore_errors: true
  register: webterminal_result
  until: webterminal_result is not failed

- name: Print webterminal_result from the previous task
  ansible.builtin.debug:
    var: webterminal_result


- name: Patch DevworkspaceTemplate for web terminal tooling
  kubernetes.core.k8s_json_patch:
    api_version: workspace.devfile.io/v1alpha2
    kind: DevWorkspaceTemplate
    name: web-terminal-tooling
    namespace: openshift-operators
    patch:
      - op: replace
        path: /spec/components/0/container/image
        value: "{{ ocp4_workload_app_connectivity_workshop_webterminal_tooling_image }}"
