---

- name: Get default SA token
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: default-token
    namespace: "{{ ocp4_workload_platform_engineering_workshop_rhdh_namespace_sa_token }}"
  register: r_default_token
  retries: 120
  delay: 10
  ignore_errors: true
  until:
    - r_default_token is defined
    - r_default_token.resources is defined
    - r_default_token.resources | length > 0
    - r_default_token.resources[0] is defined
    - r_default_token.resources[0].data is defined
    - r_default_token.resources[0].data.token is defined
    - r_default_token.resources[0].data.token | length > 0

- name: Decode default token
  ansible.builtin.set_fact:
    ocp4_workload_platform_engineering_workshop_rhdh_ocp_default_sa_token: "{{ r_default_token.resources[0].data.token | b64decode }}"

- name: Create Orchestrator application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'orchestrator/orchestrator-application.yaml.j2') | from_yaml }}"